### ISSUE TITLE
支持发送图片吗？

### ISSUE THREAD

**Issue by 1136346879** [anyRTC/ArRTM-Android#1]
您好：请问支持发送图片吗？
我们准备集成即时通讯功能

**Comment by LxzBUG** [comment]
> 您好：请问支持发送图片吗？
> 
> 我们准备集成即时通讯功能

您好，暂不支持。

可以通过业务实现，将图片上传至自己服务器后发送图片地址。

**Comment by 1136346879** [comment]
好的 谢谢
